@extends('layouts.app')

@section('title', 'Impress')

@section('content')
    <main>
        <div class="row row-simple">
            <div class="col-simple">
                <article>
                    <h1>Datenschutzverordnung</h1>
                    <p><br>Wir freuen uns sehr über Ihr Interesse an unserem Unternehmen. Diese Datenschutzerklärung soll Sie über Art, Umfang und Zweck der von uns erhobenen, genutzten und verarbeiteten personenbezogenen Daten informieren. Ferner klären wie Sie mittels dieser Datenschutzerklärung über die Ihnen zustehenden Rechte auf. Die in dieser Datenschutzerklärung verwendeten Begriffe entsprechen denen der Datenschutz-Grundverordnung (DSGVO).</p>
                    <p>Personenbezogene Daten sind alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen. Als identifizierbar wird eine natürliche Person angesehen, die direkt oder indirekt, insbesondere mittels Zuordnung zu einer Kennung wie einem Namen, zu einer Kennnummer, zu Standortdaten, zu einer Online-Kennung oder zu einem oder mehreren besonderen Merkmalen, die Ausdruck der physischen, physiologischen, genetischen, psychischen, wirtschaftlichen, kulturellen oder sozialen Identität dieser natürlichen Person sind, identifiziert werden kann.</p>
                    <p>&nbsp;</p>
                    <p><strong><br>1. Verantwortlicher</strong></p>
                    <p>Der Verantwortliche für die Datenverarbeitung im Sinne der DSGVO, sonstiger in den Mitgliedstaaten der Europäischen Union geltenden Datenschutzgesetze und anderer Bestimmungen mit datenschutzrechtlichem Charakter ist die:</p>
                    <p>Huetten-Holiday.de GmbH</p>
                    <p>gesetzlich vertreten durch:</p>
                    <p>Michael Hofer</p>
                    <p>Tel.:+49(0)9001/329999<br> (1,99 €/min aus dem dt. Festnetz, Mobilfunk ggf. abweichend)</p>
                    <p>E-Mail: service@huetten-holiday.de&nbsp;</p>
                    <p>Website: <a href="https://huetten-holiday.de">https://huetten-holiday.de</a></p>
                    <p>&nbsp;</p>
                    <p><br><strong>2. Zwecke der Datennutzung, Rechtsgrundlagen und unsere berechtigten Interessen</strong></p>
                    <p>Eine Nutzung dieser Internetseite ist grundsätzlich ohne jede Angabe personenbezogener Daten möglich. Werden solche erhoben, gilt folgendes:</p>
                    <p>&nbsp;</p>
                    <p><br><strong>a. Erfassung allgemeiner Daten und Informationen und deren Zweck</strong></p>
                    <p>Über diese Internetseite erfassen wir mit jedem Aufruf verschiedene allgemeine Daten und Informationen. Diese speichern wir in den sog. Logfiles des Servers. Erfasst werden können:</p>
                    <p>- die von Ihnen genutzten Browsertypen und Versionen, nebst den Informationen über die Art und den Typ Ihres Anzeigegerätes</p>
                    <p>- das von Ihnen genutzte Betriebssystem,</p>
                    <p>- die Internetseite, von welcher Sie auf unsere Internetseite gelangen (sogenannte Referrer),</p>
                    <p>- die Unterinternetseiten, welche über ein zugreifendes System auf unserer Internetseite angesteuert werden,</p>
                    <p>- das Datum und die Uhrzeit Ihres Aufrufs unserer Internetseite,</p>
                    <p>- Ihre Internet-Protokoll-Adresse (IP-Adresse),</p>
                    <p>- Ihr Internet-Service-Provider und</p>
                    <p>- andere ähnliche Daten und Informationen, die der Vorbeugung und Abwehr von Angriffen auf unsere IT-Systeme dienen.</p>
                    <p>Aus diesen Daten und Informationen ziehen wir keine Rückschlüsse auf Ihre Person. Wir benötigen diese Informationen um unsere Internetseite korrekt anzuzeigen, die Funktionsfähigkeit unserer IT-Systeme und unserer Internetseite zu gewährleisten sowie um Strafverfolgungsbehörden im Falle von Straftaten die zur Strafverfolgung erforderlichen Informationen zur Verfügung stellen zu können. Dies ist ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 f) DSGVO, der erforderlichenfalls die Rechtsgrundlage für eine etwaige Datenverarbeitung von personenbezogenen Daten in diesem Zusammenhang darstellt.</p>
                    <p>Die anonymen Daten der Server-Logfiles speichern wir getrennt von allen etwaigen durch Sie eingegebenen personenbezogenen Daten.</p>
                    <p>Darüber hinaus kann es vorkommen, dass die Inhalte unserer Internetseite teilweise von externen Servern geladen werden (z.B. Google-Fonts, CDN-Komponenten). Dabei werden die vorgenannten Daten auch an diese übermittelt, so dass auch dritte Zugriff auf diese erhalten. Die Nutzung dieser Komponenten erhöht die Sicherheit, Geschwindigkeit und Benutzerfreundlichkeit unserer Internetseite. Dies ist ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 f) DSGVO, der erforderlichenfalls die Rechtsgrundlage für eine etwaige Datenverarbeitung von personenbezogenen Daten in diesem Zusammenhang darstellt.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>b. Erfassung von personenbezogenen Daten und deren Zweck</strong></p>
                    <p>Auf unserer Internetseite gibt es verschiedene Möglichkeiten mit uns in Kontakt zu treten. So können Sie uns über die von uns angegebene E-Mail-Adresse kontaktieren oder hierzu ein Kontaktformular oder eine entsprechende Funktion nutzen. Bei solchen Kontaktaufnahmen speichern wir die von Ihnen eingegeben personenbezogenen Daten. Welche Daten jeweils erhoben werden, ergibt sich aus der Art der Kommunikation bzw. den Feldern des verwendeten Formulars.</p>
                    <p>Solche freiwillig von Ihnen übermittelten Daten werden von uns zum Zweck der Bearbeitung Ihrer Anfragen und/oder der Kontaktaufnahme mit Ihnen gespeichert. Wir geben personenbezogenen Daten nicht an Dritte weiter. Bei der Kontaktaufnahme mit uns erfolgt die Datenerhebung gemäß Art. 6 Abs. 1 b) DSGVO. Sie ist dann zur Durchführung vorvertraglicher Maßnahmen erforderlich. Kommt es zu einem Vertragsschluss, erfolgt die Datenerhebung ebenfalls gemäß Art. 6 Abs. 1 b) DSGVO.</p>
                    <p>Sollte die Verarbeitung personenbezogener Daten erforderlich sein und für eine solche keine gesetzliche Grundlage gemäß den vorgehend dargelegten Vorschriften vorliegen, holen wir Ihre Einwilligung ein. In solchen Fällen wäre Art. 6 Abs. 1 a) DSGVO die gesetzliche Grundlage für die Datenverarbeitung.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>c. automatisierte Entscheidungsfindung</strong></p>
                    <p>Eine automatisierte Entscheidungsfindung oder ein Profiling finden nicht statt.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>3. Dauer der Speicherung</strong></p>
                    <p>Wir speichern Ihre personenbezogenen Daten nur so lange, wie wir auf Grund entsprechender gesetzlicher Vorschriften (z.B. Steuergesetze) hierzu verpflichtet sind. Nach dem Ablauf der jeweils einschlägigen Aufbewahrungsfrist löschen wir die entsprechenden Daten routinemäßig, wenn sie nicht mehr zur Vertragserfüllung oder Vertragsanbahnung benötigt werden. Entfällt der Speicherzweck vor Ablauf einer gesetzlichen Aufbewahrungsfrist, löschen wir die entsprechenden Daten unverzüglich. Müssen wir Daten löschen, weil Interventionsrechte von Ihnen ausgeübt wurden, erfolgt dies ebenfalls unverzüglich.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>4. Ihre Rechte</strong></p>
                    <p>&nbsp;</p>
                    <p><br>a. Recht auf Bestätigung</p>
                    <p>Sie haben das Recht von uns eine Bestätigung darüber zu verlangen, ob wir Sie betreffende personenbezogene Daten verarbeiteten. Entsprechende Anfragen sind an uns zu richten. Stellen Sie die entsprechende Anfrage auf elektronischem Weg, so sind die Informationen von uns in einem gängigen elektronischen Format zur Verfügung zu stellen, sofern Sie nichts anderes angeben.</p>
                    <p>&nbsp;</p>
                    <p><br>b. Recht auf Auskunft</p>
                    <p>Werden Sie betreffende personenbezogene Daten von uns verarbeitet, haben Sie das Recht, jederzeit von uns eine kostenlose Auskunft über die zu Ihrer Person gespeicherten personenbezogenen Daten und eine Kopie dieser Daten zu erhalten. Außerdem können Sie Auskunft über folgende Informationen von uns verlangen:</p>
                    <p>- die Verarbeitungszwecke;</p>
                    <p>- die Kategorien personenbezogener Daten, die verarbeitet werden;</p>
                    <p>- die Empfänger oder Kategorien von Empfängern, gegenüber denen die personenbezogenen Daten offengelegt worden sind oder noch offengelegt werden, insbesondere bei Empfängern in Drittländern oder bei internationalen Organisationen;</p>
                    <p>- falls möglich die geplante Dauer, für die die personenbezogenen Daten gespeichert werden, oder, falls dies nicht möglich ist, die Kriterien für die Festlegung dieser Dauer;</p>
                    <p>- das Bestehen eines Rechts auf Berichtigung oder Löschung der Sie betreffenden personenbezogenen Daten oder auf Einschränkung der Verarbeitung durch uns oder eines Widerspruchsrechts gegen diese Verarbeitung;</p>
                    <p>- das Bestehen eines Beschwerderechts bei einer Aufsichtsbehörde;</p>
                    <p>- wenn die personenbezogenen Daten nicht bei Ihnen erhoben werden, alle verfügbaren Informationen über die Herkunft der Daten;</p>
                    <p>- das Bestehen einer automatisierten Entscheidungsfindung einschließlich Profiling gemäß Art. 22 Abs. 1 und 4 DSGVO und — zumindest in diesen Fällen — aussagekräftige Informationen über die involvierte Logik sowie die Tragweite und die angestrebten Auswirkungen einer derartigen Verarbeitung für Sie.</p>
                    <p>Sie haben auch ein Auskunftsrecht darüber, ob wir personenbezogene Daten an ein Drittland oder an eine internationale Organisation übermitteln. Tun wir dies, so steht Ihnen das Recht zu, über die geeigneten Garantien im Zusammenhang mit der Übermittlung unterrichtet zu werden.</p>
                    <p>Sie können sich jederzeit an uns wenden, um die vorstehend genannten Auskunftsrechte geltend zu machen. Stellen Sie die entsprechende Anfrage auf elektronischem Weg, so sind die Informationen von uns in einem gängigen elektronischen Format zur Verfügung zu stellen, sofern Sie nichts anderes angeben.</p>
                    <p>&nbsp;</p>
                    <p><br>c. Recht auf Berichtigung</p>
                    <p>Sie haben das Recht, die unverzügliche Berichtigung Sie betreffender unrichtiger personenbezogener Daten und unter Berücksichtigung der Zwecke der Verarbeitung, die Vervollständigung unvollständiger personenbezogener Daten — auch mittels einer ergänzenden Erklärung — zu verlangen. Entsprechende Anfragen sind an uns zu richten.</p>
                    <p>&nbsp;</p>
                    <p><br>d. Recht auf Löschung (Recht auf Vergessen werden)</p>
                    <p>Sie können von uns verlangen, dass die Sie betreffenden personenbezogenen Daten unverzüglich gelöscht werden, sofern einer der folgenden Gründe zutrifft:</p>
                    <p>- die personenbezogenen Daten sind für die Zwecke, für die sie erhoben oder auf sonstige Weise verarbeitet wurden, nicht mehr notwendig;</p>
                    <p>- Sie widerrufen Ihre Einwilligung, auf die sich die Verarbeitung gemäß Art. 6 Abs. 1 a) DSGVO oder Art. 9 Abs. 2 a) DSGVO stützte, und es fehlt an einer anderweitigen Rechtsgrundlage für die Verarbeitung;</p>
                    <p>- Sie legen gemäß Art. 21 Abs. 1 DSGVO Widerspruch gegen die Verarbeitung ein und es liegen keine vorrangigen berechtigten Gründe für die Verarbeitung vor, oder Sie legen gemäß Art. 21 Abs. 2 DSGVO Widerspruch gegen die Verarbeitung ein:</p>
                    <p>- die personenbezogenen Daten wurden unrechtmäßig verarbeitet:</p>
                    <p>- die Löschung der personenbezogenen Daten ist zur Erfüllung einer rechtlichen Verpflichtung nach dem Unionsrecht oder dem Recht der Mitgliedstaaten erforderlich, dem wir unterliegen oder</p>
                    <p>- die personenbezogenen Daten wurden in Bezug auf angebotene Dienste der Informationsgesellschaft gemäß Art. 8 Abs. 1 DSGVO erhoben.</p>
                    <p>Sofern einer der oben genannten Gründe zutrifft und Sie die Löschung von personenbezogenen Daten bei uns veranlassen möchten, können Sie sich hierzu jederzeit an uns wenden.</p>
                    <p>&nbsp;</p>
                    <p><br>e. Recht auf Einschränkung der Verarbeitung</p>
                    <p>Sie haben das Recht, von uns die Einschränkung der Verarbeitung zu verlangen, wenn eine der folgenden Voraussetzungen gegeben ist:</p>
                    <p>- die Richtigkeit der personenbezogenen Daten wird von Ihnen bestritten, und zwar für eine Dauer, die es uns ermöglicht, die Richtigkeit der personenbezogenen Daten zu überprüfen;</p>
                    <p>- die Verarbeitung ist unrechtmäßig, Sie lehnen die Löschung der personenbezogenen Daten ab und verlangen stattdessen die Einschränkung der Nutzung der personenbezogenen Daten;</p>
                    <p>- wir benötigen die personenbezogenen Daten für die Zwecke der Verarbeitung nicht länger, Sie benötigen sie jedoch zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder</p>
                    <p>- Sie haben Widerspruch gegen die Verarbeitung gem. Art. 21 Abs. 1 DSGVO eingelegt und es steht noch nicht fest, ob unsere berechtigten Gründe gegenüber Ihren überwiegen.</p>
                    <p>Liegt einer der vorgenannten Gründe vor und möchten Sie deshalb die Einschränkung der Verarbeitung Ihrer Daten verlangen, können Sie sich hierzu jederzeit an uns wenden.</p>
                    <p>Wurde die Verarbeitung von uns eingeschränkt, so dürfen wir diese personenbezogenen Daten – von ihrer Speicherung abgesehen – nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder aus Gründen eines wichtigen öffentlichen Interesses der Union oder eines Mitgliedstaats verarbeiten.</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p><br>f. Recht auf Datenübertragbarkeit</p>
                    <p>Sie haben das Recht, die Sie betreffenden personenbezogenen Daten, welche uns durch Sie bereitgestellt wurden, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten. Sie haben außerdem das Recht, diese Daten ohne Behinderung durch uns an Dritte zu übermitteln, sofern die Verarbeitung auf der Einwilligung gemäß Art. 6 Abs. 1 a) DSGVO oder Art. 9 Abs. 2 a) DSGVO oder auf einem Vertrag gemäß Art. 6 Abs. 1 b) DSGVO beruht und die Verarbeitung mithilfe automatisierter Verfahren erfolgt. Ferner haben Sie das Recht zu verlangen, dass die personenbezogenen Daten direkt von uns an Dritte übermittelt werden, soweit dies technisch machbar ist und sofern hiervon nicht die Rechte und Freiheiten anderer Personen beeinträchtigt werden.</p>
                    <p>Diese Rechte gelten nicht, sofern die Verarbeitung für die Wahrnehmung einer Aufgabe erforderlich ist, die im öffentlichen Interesse liegt oder in Ausübung öffentlicher Gewalt erfolgt, welche uns übertragen wurde.</p>
                    <p>Zur Geltendmachung des Rechts auf Datenübertragbarkeit können Sie sich jederzeit an uns wenden.</p>
                    <p>&nbsp;</p>
                    <p><br>g. Recht auf Widerspruch</p>
                    <p>Sie haben das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit gegen die Verarbeitung Sie betreffender personenbezogener Daten, die aufgrund von Art. 6 Abs. 1 e) oder f) DSGVO erfolgt, Widerspruch einzulegen.</p>
                    <p>Wir verarbeiten die personenbezogenen Daten im Falle des Widerspruchs nicht mehr, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die Ihren Interessen, Rechten und Freiheiten überwiegen, oder die Verarbeitung der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen dient.</p>
                    <p>Sofern personenbezogene Daten zum Zweck der Direktwerbung verarbeitet werden, können Sie auch hiergegen jederzeit Widerspruch einlegen. Wie werden dann Ihre Daten nicht mehr zu diesem Zweck weiterverarbeiten.</p>
                    <p>Zudem haben Sie das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, gegen die Sie betreffende Verarbeitung personenbezogener Daten, die bei uns zu wissenschaftlichen oder historischen Forschungszwecken oder zu statistischen Zwecken gemäß Art. 89 Abs. 1 DSGVO erfolgen, Widerspruch einzulegen, es sei denn, eine solche Verarbeitung ist zur Erfüllung einer im öffentlichen Interesse liegenden Aufgabe erforderlich.</p>
                    <p>Zur Geltendmachung Ihres Rechts auf Widerspruch können Sie sich jederzeit an uns wenden. Sie dürfen auch im Zusammenhang mit der Nutzung von Diensten der Informationsgesellschaft, ungeachtet der Richtlinie 2002/58/EG, Ihr Widerspruchsrecht mittels automatisierter Verfahren ausüben, bei denen technische Spezifikationen verwendet werden.</p>
                    <p>&nbsp;</p>
                    <p><br>h. Recht auf Widerruf einer datenschutzrechtlichen Einwilligung</p>
                    <p>Sie habe jederzeit das Recht, eine Einwilligung zur Verarbeitung personenbezogener Daten jederzeit zu widerrufen. Entsprechende Mitteilungen können Sie an uns richten. Ein Widerruf hat keinen Einfluss auf die Rechtmäßigkeit der bis zu seinem Eingang erfolgten Datenverarbeitung.</p>
                    <p>&nbsp;</p>
                    <p><br>i. Beschwerderecht</p>
                    <p>Sie haben jederzeit das Recht, Beschwerden bei der zuständigen Aufsichtsbehörde einzulegen. Hierzu müssen Sie sich an diese wenden.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>5. Weitere Informationen</strong></p>
                    <p>Bitte beachten Sie, dass die Bereitstellung personenbezogener Daten teilweise gesetzlich vorgeschrieben ist (z.B. Steuergesetze) und/oder sich aus vertraglichen Verpflichtungen ergeben kann (z.B. Daten des Vertragspartners). Sie ist auch für einen Vertragsschluss erforderlich.</p>
                    <p>Sie müssen uns personenbezogene Daten nur dann zur Verfügung stellen, wenn Sie mit uns Kontakt aufnehmen oder einen Vertrag mit uns abschließen wollen. Stellen Sie uns in solchen Fällen keine Daten zur Verfügung, können wir nicht mit Ihnen in Kontakt treten und keine Verträge abschließen.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>6. Cookies</strong></p>
                    <p>Unsere Internetseite verwendet Cookies. Cookies sind Textdateien, welche über einen Internetbrowser auf einem Computersystem abgelegt und gespeichert werden. Viele Internetseiten und Server verwenden Cookies. Der Einsatz von Cookies auf unserer Seite eröffnet uns Möglichkeiten, die Nutzung unserer Seite nutzerfreundlicher zu gestalten. Diese hätten wir ohne Cookies nicht.</p>
                    <p>Viele Cookies enthalten eine sogenannte Cookie-ID. Hierbei handelt es sich um eine eindeutige Kennung des Cookies, welche aus einer Zeichenfolge besteht. Über diese können Internetseiten und Server dem Internetbrowser zugeordnet werden, in dem das Cookie hinterlegt wurde. Diese zugeordneten Internetseiten und Server können dann einen bestimmten Internetbrowser über die eindeutige Cookie-ID wiedererkennen und identifizieren und dadurch von anderen Browsern unterscheiden.</p>
                    <p>Der Benutzer einer solchen Internetseite muss dann z.B. nicht bei jedem Aufruf erneut seine Zugangsdaten eingeben. Dies erfolgt automatisch über die entsprechende Funktion der Internetseite und den im Browser hinterlegten Cookie.</p>
                    <p>Sie können jederzeit mittels einer entsprechenden Einstellung Ihres Internetbrowsers verhindern, dass Cookies durch unsere Internetseite gesetzt werden. Damit wiedersprechen Sie der Setzung von Cookies dauerhaft. Bereits gesetzte Cookies können Sie jederzeit über die entsprechenden Funktionen Ihres Internetbrowsers oder anderer entsprechender Programme löschen. Wenn Sie diese Möglichkeit nutzen führt dies unter Umständen dazu, dass die Funktionalität unserer Internetseite eingeschränkt wird.</p>
                    <p>Die durch Cookies übermittelten Daten werden, sofern Sie für die Anzeige unserer Internetseite oder für von Ihnen genutzte Funktionen erforderlich sind, gemäß Art. 6 Abs. 1 f) DSGVO gespeichert, der die Rechtsgrundlage für die Datenverarbeitung in diesem Zusammenhang darstellt. Wir haben ein berechtigtes Interesse an der Speicherung von Cookies zur technisch fehlerfreien und optimierten Bereitstellung unserer Internetseite.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>7. Kontaktformular</strong></p>
                    <p>Wenn Sie unser Kontaktformular nutzen, um mit uns in Verbindung zu treten, speichern wir Ihre Angaben aus dem Formular bei uns, um die Bearbeitung Ihrer Anfrage und deren Beantwortung sowie etwaige Rückfragen zu ermöglichen. Durch die Nutzung des Kontaktformulars erklären Sie sich hiermit einverstanden. Sie können dieses Einverständnis jederzeit formlos (z.B. per E-Mail) widerrufen. Die Verarbeitung der Daten erfolgt in diesem Zusammenhang auf Grund Ihrer Einwilligung gemäß Art. 6 Abs. 1 a) DSGVO. Wir geben diese Daten nicht ohne Ihre Einwilligung an Dritte weiter.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>8. Newsletter</strong></p>
                    <p>Auf unserer Internetseite bieten wir einen Newsletter an. Wenn Sie diesen beziehen möchten, benötigen wir von Ihnen eine E-Mail-Adresse und weitere Informationen, mittels derer wir überprüfen können, ob Sie der Inhaber der angegebenen E-Mail-Adresse sind. Diese Daten müssen Sie über das entsprechende Formular eingeben. Sofern Sie dies tun und den Newsletter bestellen, willigen Sie in die Verarbeitung dieser Daten ein. Wir verarbeiten diese Daten nur zum Zweck des Newsletterversands und geben sie nicht an Dritte weiter.</p>
                    <p>Bei der Anmeldung zum Newsletter speichern wir außerdem die vom Internet-Service-Provider (ISP) vergebene IP-Adresse des von Ihnen zum Zeitpunkt der Anmeldung verwendeten Systems sowie das Datum und die Uhrzeit der Anmeldung. Wir benötigen diese Daten, um später etwaige Missbrauchsfälle aufklären zu können. Dies dient unserer Absicherung und liegt im unserem berechtigten Interesse. Die Verarbeitung dieser Daten erfolgt daher gemäß Art. 6 Abs. 1 f) DSGVO.</p>
                    <p>Rechtsgrundlage für die Verarbeitung der von Ihnen eingegebenen Daten, ist die von Ihnen durch die Bestellung des Newsletters erteilte Einwilligung gemäß Art. 6 Abs. 1 a) DSGVO. Diese können Sie jederzeit formlos widerrufen, etwa mittels des in jeder Newsletter-E-Mail befindlichen Links zur Abbestellung des Newsletters. Ebenso können Sie den Newsletter abbestellen. Die bis zum Widerruf verarbeiteten Daten gelten auch nach einem solchen Widerruf als rechtmäßig verarbeitet.</p>
                    <p>Wir speichern die von Ihnen bei der Bestellung des Newsletters bei uns hinterlegten Daten, bis Sie den Newsletter wieder abbestellen. Nach der Abbestellung des Newsletters löschen wir sie. Solche Daten, welche auch zu anderen Zwecken von uns gespeichert wurden, sind hiervon nicht betroffen.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>9. Kommentarfunktion im Blog auf der Internetseite</strong></p>
                    <p>Die test bietet den Nutzern auf einem Blog, der sich auf der Internetseite des für die Verarbeitung Verantwortlichen befindet, die Möglichkeit, individuelle Kommentare zu einzelnen Blog-Beiträgen zu hinterlassen. Ein Blog ist ein auf einer Internetseite geführtes, in der Regel öffentlich einsehbares Portal, in welchem eine oder mehrere Personen, die Blogger oder Web-Blogger genannt werden, Artikel posten oder Gedanken in sogenannten Blogposts niederschreiben können. Die Blogposts können in der Regel von Dritten kommentiert werden.</p>
                    <p>&nbsp;</p>
                    <p><br>Hinterlässt eine betroffene Person einen Kommentar in dem auf dieser Internetseite veröffentlichten Blog, werden neben den von der betroffenen Person hinterlassenen Kommentaren auch Angaben zum Zeitpunkt der Kommentareingabe sowie zu dem von der betroffenen Person gewählten Nutzernamen (Pseudonym) gespeichert und veröffentlicht. Ferner wird die vom Internet-Service-Provider (ISP) der betroffenen Person vergebene IP-Adresse mitprotokolliert. Diese Speicherung der IP-Adresse erfolgt aus Sicherheitsgründen und für den Fall, dass die betroffene Person durch einen abgegebenen Kommentar die Rechte Dritter verletzt oder rechtswidrige Inhalte postet. Die Speicherung dieser personenbezogenen Daten erfolgt daher im eigenen Interesse des für die Verarbeitung Verantwortlichen, damit sich dieser im Falle einer Rechtsverletzung gegebenenfalls exkulpieren könnte. Es erfolgt keine Weitergabe dieser erhobenen personenbezogenen Daten an Dritte, sofern eine solche Weitergabe nicht gesetzlich vorgeschrieben ist oder der Rechtsverteidigung des für die Verarbeitung Verantwortlichen dient.</p>
                    <p>&nbsp;</p>
                    <p><br><strong>10. Datenschutzerklärung für die Nutzung von Google Analytics</strong></p>
                    <p>Diese Website nutzt Funktionen des Webanalysedienstes Google Analytics. Anbieter ist die Google Inc., 1600 Amphitheatre Parkway Mountain View, CA 94043, USA.</p>
                    <p>Google Analytics verwendet sog. "Cookies". Das sind Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen. Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert.</p>
                    <p>Im Falle der Aktivierung der IP-Anonymisierung auf dieser Webseite wird Ihre IP-Adresse von Google jedoch innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Im Auftrag des Betreibers dieser Website wird Google diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.</p>
                    <p>Sie können die Speicherung der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich werden nutzen können. Sie können darüber hinaus die Erfassung der durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten (inkl. Ihrer IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verfügbare Browser-Plugin herunterladen und installieren:&nbsp;http://tools.google.com/dlpage/gaoptout?hl=de</p>
                    <p>Sie können die Erfassung durch Google Analytics verhindern, indem Sie auf folgenden Link klicken. Es wird ein Opt-Out-Cookie gesetzt, das das Erfassung Ihrer Daten bei zukünftigen Besuchen dieser Website verhindert.</p>
                    <p><a href="javascript:gaOptout()">Google Analytics deaktivieren</a></p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;<br><strong>11.Datenschutzbestimmungen zu Einsatz und Verwendung von Facebook</strong></p>
                    <p>Der für die Verarbeitung Verantwortliche hat auf dieser Internetseite Komponenten des Unternehmens Facebook integriert. Facebook ist ein soziales Netzwerk.</p>
                    <p>Ein soziales Netzwerk ist ein im Internet betriebener sozialer Treffpunkt, eine Online-Gemeinschaft, die es den Nutzern in der Regel ermöglicht, untereinander zu kommunizieren und im virtuellen Raum zu interagieren. Ein soziales Netzwerk kann als Plattform zum Austausch von Meinungen und Erfahrungen dienen oder ermöglicht es der Internetgemeinschaft, persönliche oder unternehmensbezogene Informationen bereitzustellen. Facebook ermöglicht den Nutzern des sozialen Netzwerkes unter anderem die Erstellung von privaten Profilen, den Upload von Fotos und eine Vernetzung über Freundschaftsanfragen.</p>
                    <p>Betreibergesellschaft von Facebook ist die Facebook, Inc., 1 Hacker Way, Menlo Park, CA 94025, USA. Für die Verarbeitung personenbezogener Daten Verantwortlicher ist, wenn eine betroffene Person außerhalb der USA oder Kanada lebt, die Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland.</p>
                    <p>Durch jeden Aufruf einer der Einzelseiten dieser Internetseite, die durch den für die Verarbeitung Verantwortlichen betrieben wird und auf welcher eine Facebook-Komponente (Facebook-Plug-In) integriert wurde, wird der Internetbrowser auf dem informationstechnologischen System der betroffenen Person automatisch durch die jeweilige Facebook-Komponente veranlasst, eine Darstellung der entsprechenden Facebook-Komponente von Facebook herunterzuladen. Eine Gesamtübersicht über alle Facebook-Plug-Ins kann unter <a href="https://developers.facebook.com/docs/plugins/?locale=de_DE">https://developers.facebook.com/docs/plugins/?locale=de_DE</a>&nbsp;abgerufen werden. Im Rahmen dieses technischen Verfahrens erhält Facebook Kenntnis darüber, welche konkrete Unterseite unserer Internetseite durch die betroffene Person besucht wird.</p>
                    <p>Sofern die betroffene Person gleichzeitig bei Facebook eingeloggt ist, erkennt Facebook mit jedem Aufruf unserer Internetseite durch die betroffene Person und während der gesamten Dauer des jeweiligen Aufenthaltes auf unserer Internetseite, welche konkrete Unterseite unserer Internetseite die betroffene Person besucht. Diese Informationen werden durch die Facebook-Komponente gesammelt und durch Facebook dem jeweiligen Facebook-Account der betroffenen Person zugeordnet. Betätigt die betroffene Person einen der auf unserer Internetseite integrierten Facebook-Buttons, beispielsweise den „Gefällt mir“-Button, oder gibt die betroffene Person einen Kommentar ab, ordnet Facebook diese Information dem persönlichen Facebook-Benutzerkonto der betroffenen Person zu und speichert diese personenbezogenen Daten.</p>
                    <p>Facebook erhält über die Facebook-Komponente immer dann eine Information darüber, dass die betroffene Person unsere Internetseite besucht hat, wenn die betroffene Person zum Zeitpunkt des Aufrufs unserer Internetseite gleichzeitig bei Facebook eingeloggt ist; dies findet unabhängig davon statt, ob die betroffene Person die Facebook-Komponente anklickt oder nicht. Ist eine derartige Übermittlung dieser Informationen an Facebook von der betroffenen Person nicht gewollt, kann diese die Übermittlung dadurch verhindern, dass sie sich vor einem Aufruf unserer Internetseite aus ihrem Facebook-Account ausloggt.</p>
                    <p>Die von Facebook veröffentlichte Datenrichtlinie, die unter <a href="https://de-de.facebook.com/about/privacy/">https://de-de.facebook.com/about/privacy/</a>&nbsp;abrufbar ist, gibt Aufschluss über die Erhebung, Verarbeitung und Nutzung personenbezogener Daten durch Facebook. Ferner wird dort erläutert, welche Einstellungsmöglichkeiten Facebook zum Schutz der Privatsphäre der betroffenen Person bietet. Zudem sind unterschiedliche Applikationen erhältlich, die es ermöglichen, eine Datenübermittlung an Facebook zu unterdrücken. Solche Applikationen können durch die betroffene Person genutzt werden, um eine Datenübermittlung an Facebook zu unterdrücken.</p>
                    <p>&nbsp;</p>
                    <p><strong>12. Zahlungsart: Datenschutzbestimmungen zu Klarna als Zahlungsart<br></strong><br>Der für die Verarbeitung Verantwortliche hat auf dieser Internetseite Komponenten von Klarna integriert. Klarna ist ein Online-Zahlungsdienstleister, der den Kauf auf Rechnung oder eine flexible Ratenzahlung ermöglicht. Ferner werden von Klarna weitere Services, wie beispielsweise ein Käuferschutz oder eine Identitäts- und Bonitätsprüfung, angeboten.</p>
                    <p>Betreibergesellschaft von Klarna ist die Klarna AB, Sveavägen 46, 111 34 Stockholm, Schweden.</p>
                    <p>Wählt die betroffene Person während des Bestellvorgangs in unserem Online-Shop als Zahlungsmöglichkeit entweder den „Kauf auf Rechnung“ oder „Ratenkauf“ aus, werden automatisiert Daten der betroffenen Person an Klarna übermittelt. Mit der Auswahl einer dieser Zahlungsoptionen willigt die betroffene Person in diese, zur Abwicklung des Rechnungs- oder Ratenkaufes oder zur Identitäts- und Bonitätsprüfung erforderliche, Übermittlung personenbezogener Daten ein.&nbsp;</p>
                    <p>Bei den an Klarna übermittelten personenbezogenen Daten handelt es sich in der Regel um Vorname, Nachname, Adresse, Geburtsdatum, Geschlecht, Email-Adresse, IP-Adresse, Telefonnummer, Mobiltelefonnummer sowie um andere Daten, die zur Abwicklung eines Rechnungs- oder Ratenkaufs notwendig sind. Zur Abwicklung des Kaufvertrages notwendig sind auch solche personenbezogenen Daten, die im Zusammenhang mit der jeweiligen Bestellung stehen. Insbesondere kann es zum wechselseitigen Austausch von Zahlungsinformationen, wie Bankverbindung, Kartennummer, Gültigkeitsdatum und CVC-Code, Artikelanzahl, Artikelnummer, Daten zu Waren und Dienstleistungen, Preise und steuerliche Abgaben, Angaben zum früheren Kaufverhalten oder sonstige Angaben zur finanziellen Situation der betroffenen Person, kommen.&nbsp;</p>
                    <p>Die Übermittlung der Daten bezweckt insbesondere die Identitätsüberprüfung, die Zahlungsadministration und die Betrugsprävention. Der für die Verarbeitung Verantwortliche wird Klarna personenbezogene Daten insbesondere dann übermitteln, wenn ein berechtigtes Interesse für die Übermittlung gegeben ist. Die zwischen Klarna und dem für die Verarbeitung Verantwortlichen ausgetauschten personenbezogenen Daten werden von Klarna an Wirtschaftsauskunfteien übermittelt. Diese Übermittlung bezweckt die Identitäts- und Bonitätsprüfung.</p>
                    <p>Klarna gibt die personenbezogenen Daten auch an verbundene Unternehmen (Klarna Gruppe) und Leistungserbringer oder Subunternehmer weiter, soweit dies zur Erfüllung der vertraglichen Verpflichtungen erforderlich ist oder die Daten im Auftrag verarbeitet werden sollen.</p>
                    <p>Zur Entscheidung über die Begründung, Durchführung oder Beendigung einer Vertragsbeziehung erhebt und nutzt Klarna Daten und Informationen über das bisherige Zahlungsverhalten der betroffenen Person sowie Wahrscheinlichkeitswerte für deren Verhalten in der Zukunft (sogenanntes Scoring). Die Berechnung des Scorings wird auf der Basis wissenschaftlich anerkannter mathematisch-statistischer Verfahren durchgeführt.&nbsp;</p>
                    <p>Die betroffene Person hat die Möglichkeit, die Einwilligung zum Umgang mit personenbezogenen Daten jederzeit gegenüber Klarna zu widerrufen. Ein Widerruf wirkt sich nicht auf personenbezogene Daten aus, die zwingend zur (vertragsgemäßen) Zahlungsabwicklung verarbeitet, genutzt oder übermittelt werden müssen.&nbsp;</p>
                    <p>Die geltenden Datenschutzbestimmungen von Klarna können unter <a href="https://cdn.klarna.com/1.0/shared/content/policy/data/de_de/data_protection.pd">https://cdn.klarna.com/1.0/shared/content/policy/data/de_de/data_protection.pd</a>f abgerufen werden.</p>
                    <p>&nbsp;</p>
                    <p><strong>13. Zahlungsart: Datenschutzbestimmungen zu PayPal als Zahlungsart<br></strong><br>Der für die Verarbeitung Verantwortliche hat auf dieser Internetseite Komponenten von PayPal integriert. PayPal ist ein Online-Zahlungsdienstleister. Zahlungen werden über sogenannte PayPal-Konten abgewickelt, die virtuelle Privat- oder Geschäftskonten darstellen. Zudem besteht bei PayPal die Möglichkeit, virtuelle Zahlungen über Kreditkarten abzuwickeln, wenn ein Nutzer kein PayPal-Konto unterhält. Ein PayPal-Konto wird über eine E-Mail-Adresse geführt, weshalb es keine klassische Kontonummer gibt. PayPal ermöglicht es, Online-Zahlungen an Dritte auszulösen oder auch Zahlungen zu empfangen. PayPal übernimmt ferner Treuhänderfunktionen und bietet Käuferschutzdienste an.</p>
                    <p>Die Europäische Betreibergesellschaft von PayPal ist die PayPal (Europe) S.à.r.l. &amp; Cie. S.C.A., 22-24 Boulevard Royal, 2449 Luxembourg, Luxemburg.</p>
                    <p>Wählt die betroffene Person während des Bestellvorgangs in unserem Online-Shop als Zahlungsmöglichkeit „PayPal“ aus, werden automatisiert Daten der betroffenen Person an PayPal übermittelt. Mit der Auswahl dieser Zahlungsoption willigt die betroffene Person in die zur Zahlungsabwicklung erforderliche Übermittlung personenbezogener Daten ein.</p>
                    <p>Bei den an PayPal übermittelten personenbezogenen Daten handelt es sich in der Regel um Vorname, Nachname, Adresse, Email-Adresse, IP-Adresse, Telefonnummer, Mobiltelefonnummer oder andere Daten, die zur Zahlungsabwicklung notwendig sind. Zur Abwicklung des Kaufvertrages notwendig sind auch solche personenbezogenen Daten, die im Zusammenhang mit der jeweiligen Bestellung stehen.</p>
                    <p>Die Übermittlung der Daten bezweckt die Zahlungsabwicklung und die Betrugsprävention. Der für die Verarbeitung Verantwortliche wird PayPal personenbezogene Daten insbesondere dann übermitteln, wenn ein berechtigtes Interesse für die Übermittlung gegeben ist. Die zwischen PayPal und dem für die Verarbeitung Verantwortlichen ausgetauschten personenbezogenen Daten werden von PayPal unter Umständen an Wirtschaftsauskunfteien übermittelt. Diese Übermittlung bezweckt die Identitäts- und Bonitätsprüfung.</p>
                    <p>PayPal gibt die personenbezogenen Daten gegebenenfalls an verbundene Unternehmen und Leistungserbringer oder Subunternehmer weiter, soweit dies zur Erfüllung der vertraglichen Verpflichtungen erforderlich ist oder die Daten im Auftrag verarbeitet werden sollen.</p>
                    <p>Die betroffene Person hat die Möglichkeit, die Einwilligung zum Umgang mit personenbezogenen Daten jederzeit gegenüber PayPal zu widerrufen. Ein Widerruf wirkt sich nicht auf personenbezogene Daten aus, die zwingend zur (vertragsgemäßen) Zahlungsabwicklung verarbeitet, genutzt oder übermittelt werden müssen.&nbsp;</p>
                    <p>Die geltenden Datenschutzbestimmungen von PayPal können unter <a href="https://www.paypal.com/de/webapps/mpp/ua/privacy-full">https://www.paypal.com/de/webapps/mpp/ua/privacy-full</a> abgerufen werden.</p>
                    <p>&nbsp;</p>
                    <p><strong>14. Zahlungsart: Datenschutzbestimmungen zu Sofortüberweisung als Zahlungsart<br></strong><br>Der für die Verarbeitung Verantwortliche hat auf dieser Internetseite Komponenten von Sofortüberweisung integriert. Sofortüberweisung ist ein Zahlungsdienst, der eine bargeldlose Zahlung von Produkten und Dienstleistungen im Internet ermöglicht. Sofortüberweisung bildet ein technisches Verfahren ab, durch welches der Online-Händler unverzüglich eine Zahlungsbestätigung erhält. So wird ein Händler in die Lage versetzt, Waren, Dienstleistungen oder Downloads sofort nach der Bestellung an den Kunden auszuliefern.</p>
                    <p>Betreibergesellschaft von Sofortüberweisung ist die SOFORT GmbH, Fußbergstraße 1, 82131 Gauting, Deutschland.</p>
                    <p>Wählt die betroffene Person während des Bestellvorgangs in unserem Online-Shop als Zahlungsmöglichkeit „Sofortüberweisung“ aus, werden automatisiert Daten der betroffenen Person an Sofortüberweisung übermittelt. Mit einer Auswahl dieser Zahlungsoption willigt die betroffene Person in eine zur Zahlungsabwicklung erforderliche Übermittlung personenbezogener Daten ein.</p>
                    <p>Bei der Kaufabwicklung über Sofortüberweisung übermittelt der Käufer die PIN und die TAN an die Sofort GmbH. Sofortüberweisung führt sodann nach technischer Überprüfung des Kontostandes und Abruf weiterer Daten zur Prüfung der Kontodeckung eine Überweisung an den Online-Händler aus. Die Durchführung der Finanztransaktion wird dem Online-Händler sodann automatisiert mitgeteilt.</p>
                    <p>Bei den mit Sofortüberweisung ausgetauschten personenbezogenen Daten handelt es sich um Vorname, Nachname, Adresse, Email-Adresse, IP-Adresse, Telefonnummer, Mobiltelefonnummer oder andere Daten, die zur Zahlungsabwicklung notwendig sind. Die Übermittlung der Daten bezweckt die Zahlungsabwicklung und die Betrugsprävention. Der für die Verarbeitung Verantwortliche wird Sofortüberweisung andere personenbezogene Daten auch dann übermitteln, wenn ein berechtigtes Interesse für die Übermittlung gegeben ist. Die zwischen Sofortüberweisung und dem für die Verarbeitung Verantwortlichen ausgetauschten personenbezogenen Daten werden von Sofortüberweisung unter Umständen an Wirtschaftsauskunfteien übermittelt. Diese Übermittlung bezweckt die Identitäts- und Bonitätsprüfung.</p>
                    <p>Sofortüberweisung gibt die personenbezogenen Daten gegebenenfalls an verbundene Unternehmen und Leistungserbringer oder Subunternehmer weiter, soweit dies zur Erfüllung der vertraglichen Verpflichtungen erforderlich ist oder die Daten im Auftrag verarbeitet werden sollen.</p>
                    <p>Die betroffene Person hat die Möglichkeit, die Einwilligung zum Umgang mit personenbezogenen Daten jederzeit gegenüber Sofortüberweisung zu widerrufen. Ein Widerruf wirkt sich nicht auf personenbezogene Daten aus, die zwingend zur (vertragsgemäßen) Zahlungsabwicklung verarbeitet, genutzt oder übermittelt werden müssen.</p>
                    <p>Die geltenden Datenschutzbestimmungen von Sofortüberweisung können unter <a href="https://www.sofort.com/ger-DE/datenschutzerklaerung-sofort-gmbh/">https://www.sofort.com/ger-DE/datenschutzerklaerung-sofort-gmbh/</a> abgerufen werden.</p>
                </article>
            </div>
        </div><br /><br />
    </main>
@endsection

