@extends('layouts.app')

@section('title', 'Terms & Conditions')

@section('content')
    <main>
        <div class="row row-simple">
            <div class="col-simple">
                <article>
                    <h1>Allgemeine Geschäftsbedingungen</h1>
                    <br />
                    <p>Die Huetten-Holiday.de GmbH betreibt unter Huetten-Holiday.de einen europaweiten Berghüttensuch- und reservierungs-service. Es gelten die folgenden Teilnahmebedingungen von Huetten-Holiday.de, nachfolgend „Vermittler“ genannt.</p>
                    <br />
                </article>
                <article>
                    <ol>
                        <li><strong>Geltungsbereich</strong>
                            <p>Diese Allgemeinen Geschäftsbedingungen gelten für alle unverbindlichen Reservierungsanfragen, Reservierungen und Buchungen über das Reservierungssystem des Vermittlers.</p>
                        </li>
                        <li><strong>Inhalt der Dienstleistung sowie Gutscheinbedingungen</strong>
                            <ol>
                                <li>Inhalt der Dienstleistung ist die Vermittlung und der Abschluss eines Beherbergungsvertrages, der während einer Buchung unmittelbar zwischen Ihnen und der von Ihnen ausgesuchten Berghütte zustande kommt. Mit der verbindlichen Buchung wird eine Anzahlung fällig. Hierfür erhalten Sie vom Vermittler einen Voucher (Wertgutschein) für die von Ihnen ausgesuchte Berghütte im Wert der Anzahlung. Den Voucher erhalten Sie zum Selbstausdruck in digitaler Form an die von Ihnen angegebene E-Mail-Adresse. Zum Abschluss des Reservierungsvorganges wird Ihnen eine PDF-Datei angezeigt, in der ein individueller Barcode und eine individuelle Wertgutscheinnummer abgebildet sind, mit denen die Eindeutigkeit des Wertgutscheins gewährleistet wird. Sie können diese PDF-Datei ausdrucken und auch abspeichern.</li>
                                <li>Der Wertgutschein ist frei übertragbar und kann vom jeweiligen Inhaber bei der von Ihnen ausgesuchten Berghütte eingelöst werden. Er stellt ein Zahlungsmittel entsprechend der Höhe des Nennwertes dar. Die von Ihnen ausgesuchte Berghütte löst den Wertgutschein demjenigen gegenüber ein, der sie an der Rezeption der von Ihnen ausgesuchten Berghütte vorlegt. Im Falle fristgerechter Stornierung Ihrer Buchung, ist der Wertgutschein vier Jahre gültig. Während dieser Gültigkeitsdauer kann der Wert des jeweiligen Wertgutscheins verwendet werden. Die Gültigkeitsdauer übersteigt damit die gesetzliche Verjährungsfrist.</li>
                                <li>Erscheinen Sie bzw. erscheint der jeweilige Inhaber des Wertgutscheins nicht zum reservierten Buchungstermin, verliert der Gutschein seine Gültigkeit. Dies gilt jedoch nicht, soweit höhere Gewalt vorliegt, die es für Sie bzw. für den jeweiligen Inhaber des Gutscheines unmöglich macht, am Reservierungsdatum eine Wanderung zu der von Ihnen ausgesuchten Berghütte zu unternehmen. Die Beweislast für das Vorliegen von höherer Gewalt tragen Sie bzw. der jeweilige Inhaber des Wertgutscheins. Des Weiteren gilt dies nicht, wenn Sie (bzw. der jeweilige Inhaber) die Reservierung rechtzeitig bzw. kostenfrei stornieren.</li>
                                <li>Die entsprechenden Stornozeitpunkte entnehmen Sie bitte den Detailseiten der jeweiligen Berghütten. Beachten Sie hierzu auch unsere Ausführungen unten unter 4.2. Verbindlichkeit Ihrer Reservierung, Änderungen und Stornierungen. Es gibt unterschiedliche Stornierungszeitpunkte:
                                    <p>Beispiele:</p>
                                    <p>Stornierungen, die bis mindestens zu zwei Tage vor Anreisedatum erfolgen, sind kostenfrei (z.B. Samstag Anreisetag; kostenfreie Stornierung bis Donnerstag 23:59 möglich);</p>
                                </li>
                                <li>Den mit der verbindlichen Reservierung bestätigten Preis bezahlen Sie direkt auf der Berghütte. Die von Ihnen geleistete Anzahlung wird von der Gesamtsumme der Reservierung abgezogen, soweit Sie den erhaltenen Voucher an der Rezeption der von Ihnen ausgesuchten Berghütte vorlegen. Sämtliche sich aus dem Beherbergungsvertrag ergebenden Ansprüche und Verpflichtungen bestehen unmittelbar und ausschließlich zwischen Ihnen und der von Ihnen ausgesuchten Unterkunft. Ein Beherbergungsvertragsverhältnis zwischen Ihnen und dem Vermittler besteht nicht. Der Vermittler informiert Sie auf dessen Webseite über eine Auswahl einzelner Leistungen. Wenn Sie eine Leistung buchen möchten, so nimmt der Vermitt-ler Ihren Reservierungsantrag entgegen. Ist dem Vermittler bekannt, dass die gebuchte Leistung verfügbar ist, so nimmt der Vermittler die Reservierung beim Anbieter vor und übermittelt Ihnen die Reservierungsbestätigung. Ansonsten übermit-telt der Vermittler Ihren Reservierungsantrag an den jeweiligen Anbieter sowie die Antwort des Anbieters hierauf. Anbieter der Leistungen („Anbieter“) ist nicht der Vermittler, sondern der Berghüttenbetreiber / Unterkunftsbetreiber. Buchen Sie mehrere Leistungen über die Internetseiten des Vermittlers, so erfolgen Auswahl und Zusammenstellung der einzelnen Leistungen nicht durch den Reservierungssystembetreiber, sondern in eigener Verantwortung. Bei der Auswahl einzelner vom Reservierungssystem vorgeschlagenen Leistungen werden die von Ihnen angegebenen Bedingungen (z.B. Ort, Ziel, Preis, Zeitraum, Kategorie) so gut wie möglich berücksichtigt. Die vom Reservierungssystem getroffene Auswahl ist je-doch nicht so zu verstehen, dass es daneben keine anderen oder besseren Reiseleistungen gäbe, die Ihren Wünschen oder Bedingungen entsprechen könnten.</li>
                            </ol>
                        </li>
                        <li><strong>Vertrag zwischen Ihnen und dem Anbieter der Reiseleistung</strong>
                            <p>Durch die Benutzung des Reservierungssystems kommt zwischen Ihnen und dem Anbieter der jeweiligen Leistung ein Beherbergungsvertrag zustande („der Vertrag“). Der Vertrag kommt mit erfolgreichem Abschluss des Online-Reservierungsvorgangs verbindlich zustande. Der Reservierungssystembetreiber und der Vermittler übermitteln lediglich als Bote die Erklärungen zwischen Ihnen und dem Anbieter. Der Reservierungssystembetreiber und der Vermittler werden im Verhältnis zu Ihnen und zum Anbieter als unabhängiger Dritter tätig, und nicht als Partner, Treuhänder, Vertreter oder Subunternehmer von Ihnen oder vom Anbieter. Für die Abwicklung des Vertrages sind der Reservierungssystembetreiber und der Vermittler nicht verantwortlich.</p>
                        </li>
                        <li><strong>Inhalt der Reservierung</strong>
                            <ol>
                                <li>Standard-Buchungen von Berghütten<br> Die Standard-Buchung wird von den Herbergen grundsätzlich bis 18:00 Uhr Ortszeit aufrechterhalten. Bei Nicht-Anreise bis 18:00 Uhr Ortszeit kann die reservierte Unterkunft evtl. nicht eingehalten werden und der Berghüttenbetreiber teilt Ihnen einen anderen Schlafplatz (ggf. auch Notschlafplatz) zu. Ein Anspruch auf Unterbringung besteht nach 18:00 Uhr Ortszeit ausdrücklich nicht mehr. Zudem sind hierbei die Hinweise der jeweiligen Herberge während des Buchungsdialo-ges zu beachten.</li>
                                <li>Verbindlichkeit Ihrer Reservierungen, Änderungen und Stornierungen<br> Wenn Sie Ihre Reservierung nicht rechtzeitig stornieren oder den Berghüttenaufenthalt ohne Stornierung nicht in Anspruch genommen haben, verliert der von Ihnen erworbene Wertgutschein seine Gültigkeit. In diesem Fall verfällt Ihre Anzahlung. Die detaillierten Stornierungsbedingungen sind auf den Detailseiten der jeweiligen Berghütten ersichtlich und werden von Ihnen akzeptiert. Stornierungen erfolgen über das Onlineportal des Vermittlers. Im Falle einer Stornierung direkt bei der Berghütte kann der Vermittler keine Auskünfte geben zu etwaigen Unstimmigkeiten hinsichtlich des Stornierungszeitpunk-tes oder den Stornierungstatbestand durch den Buchungskunden. Wünscht der Buchungskunde eine Änderung einer be-reits getätigten Buchung (sogenannte Umbuchung) und tritt er dazu per E-Mail oder telefonisch mit dem Vermittler in Kon-takt, so ist der Vermittler berechtigt, die persönlichen Daten des Kunden zu speichern, um die Umbuchung – soweit möglich - durchzuführen. Die Rechte des Kunden auf Löschung seiner Daten gemäß den Huetten-Holiday.de - Datenschutzbestim-mungen bleiben davon unberührt. Der Vermittler behält sich das Recht vor, bei Reservierungen mit unvollständigen, zwei-felhaften oder augenscheinlich falschen Daten der buchenden oder der reisenden Person die Reservierung ohne Rück-sprache mit dem Buchungskunden zu stornieren. Dieses Recht besteht auch bei Buchungen von Personen oder Registrie-rungen, die in der Vergangenheit des Öfteren mit sogenannten No-Shows (Nichtanreise ohne Stornierung) oder nicht / nicht vollständig bezahlten Rechnungen aufgefallen sind. In beiden Fällen besteht kein Anrecht auf Umsetzung der Buchung. Der Vermittler empfiehlt den Abschluss geeigneter Reiseversicherungen, insbesondere einer Reiserücktrittskosten- und / oder Ersatzreiseversicherung.</li>
                                <li>Vertraglich vereinbarte Zimmerpreise<br> Alle Preise sind aktuelle Tagespreise, die im Namen der jeweiligen Berghütte angezeigt werden und die für alle über das weltweite Reservierungssystem des Vermittlers durchgeführten Buchungen gelten. Der Preis wird durch die Berghütte mitgeteilt und enthält die jeweiligen Steuern und Gebühren. Soweit Steuern und Gebühren angegeben werden, handelt es sich um im Preis enthaltene Steuern und Gebühren. Die Höhe der angegebenen Steuern ist ständigen Änderungen unter-worfen und kann deshalb nur unverbindlich angegeben werden. Für bestimmte Destinationen können zusätzliche ortsübli-che Abgaben wie z.B. Kurtaxe (City Tax) fällig werden. Die genannten Preise gelten für einen Schlafplatz im Betten- oder Matratzenlager und für eine Nacht, ohne Nebenleistungen. Die gebotenen Nebenleistungen hängen von der jeweiligen Berghütte ab. Ein Frühstück ist nur dann im Zimmerpreis enthalten, wenn dies in der Unterkunftsbeschreibung oder auf der Internetseite der Unterkunft gesondert angegeben wird. Preisangaben in anderen Währungen können Wechselkurs-schwankungen unterliegen und werden daher ohne Gewähr und ausschließlich zur Orientierung angezeigt. Der Beherber-gungsvertrag und die Abrechnung erfolgt direkt mit dem Unterkunftsbetreiber.</li>
                                <li>Pass-, Visum-, Zoll-, Devisen- und Gesundheitsvorschriften der Reiseleistung<br> Der Vermittler vermittelt nur einzelne Reiseleistungen und ist über die Einzelheiten Ihrer Reise und Ihrer persönlichen Verhältnisse (z.B. Staatsangehörigkeit) nicht informiert. Der Vermittler kann deswegen die einschlägigen Pass-, Visum-, Zoll-, Devisen- und Gesundheitsvorschriften nicht feststellen, so dass Sie für die Einhaltung aller eventuell zu beachten-den Vorschriften selbst verantwortlich sind.</li>
                                <li>Zusammenfassung von gleichen Einzelbuchungen<br> Wird durch zeitlich aufeinanderfolgende oder parallel getätigte Einzelbuchungen durch einen Kunden oder eine Kunden-Gruppe eine Gruppenbuchung erzeugt, hat die Berghütte oder der Vermittler das Recht, die Einzelbuchungen zu einer Gruppenbuchung zusammenzufassen und die Buchungs- und Stornierungsbedingungen zu modifizieren. Sollten die neuen Bedingungen vom Buchenden nicht akzeptiert werden, hat die Berghütte oder der Vermittler das Recht, die Buchungen zu stornieren. Des Weiteren können Sie Ihren Anspruch auf die reservierte Reiseleistung nur mit ausdrücklicher Zustimmung des Anbieters an eine andere Person abtreten. Bei fehlender bzw. zweifelhafter Angabe der reisenden Person(en) behält sich der Vermittler das Recht vor, Reservierungen ohne Rücksprache mit dem Buchenden zu stornieren.</li>
                            </ol>
                        </li>
                        <li><strong>Bezahlung</strong>
                            <ol>
                                <li>Die Anzahlung für den Erwerb eines Vouchers bezahlen Sie über den Online-Anbieter Payone GmbH, Fraunhoferstraße 2-4, 24118 Kiel (<a href="http://www.payone.de" target="_blank" rel="noopener">www.payone.de</a>) und an dessen Partner.</li>
                                <li>Sie müssen dort nicht registriert sein. Sie geben lediglich Ihre Daten in die Maske ein, bestätigen diese und gehen dann zur Kasse. Dazu werden von Ihnen seitens der Payone GmbH, die von uns mit der Abwicklung der Zahlungen beauftragt worden ist, bestimmte, u.a. persönliche Informationen, benötigt. Es handelt sich dabei um Name und Anschrift des Kunden, sowie Kontonummer, Bankleitzahl oder Kreditkartennummer (auch der Gültigkeitszeitraum), den Rechnungsbetrag und Währung und die Transaktionsnummer. Die Payone GmbH darf die oben genannten Informationen zum Zwecke der Zah-lungsabwicklung verwenden und an seine Partner zur Verarbeitung weiterreichen und wir dürfen diese Daten an die Payone GmbH weitergeben. Zu diesem Zweck stimmen Sie der Speicherung, Verarbeitung und Nutzung der uns durch Ihre Bestel-lung übermittelten personenbezogenen Daten zum Zwecke der Ausführung Ihrer Bestellung zu. Die Payone GmbH ist verpflichtet diese Informationen gemäß den deutschen Datenschutzgesetzen zu behandeln. Auf den Servern von Huet-ten-Holiday.de werden weder Ihre Kontoverbindungsdaten noch Ihre Kreditkartendaten gespeichert.</li>
                                <li>Pro Reservierung fällt eine Service-Gebühr in Höhe von 12,5 % der jeweiligen Anzahlung an (z. B. Anzahlung von EUR 10,00; Transaktionsgebühr von EUR 1,25). Wurde die Reservierung rechtzeitig storniert, fällt die Service-Gebühr kein weiteres Mal an.<br> Die Service-Gebühr wird vom Gast bezahlt, wenn dieser Buchungen über die Huetten-Holiday.de Webseite vornimmt. Diese Gebühr dient zur Kostendeckung für den Betrieb der Website. Die Betriebskosten für Huetten-Holiday.de beinhalten unter anderem die Vereinfachung sicherer Buchungen, Entwicklung unserer Produkte und Services. Die Servicegebühren enthalten auch Transaktionskosten von Drittanbietern, diese werden jedoch ohne Aufschlag an den Gast weitergegeben.</li>
                                <li>Der gesamte Reservierungsprozess wird über eine gesicherte https-Verbindung abgewickelt. Weitere Hinweise erhalten Sie beim Bestellvorgang.</li>
                            </ol>
                        </li>
                        <li><strong>Widerrufs- und Rückgaberecht</strong>
                            <p>Soweit es sich bei dem Kunden um einen Verbraucher im Sinne des § 13 BGB handelt und es sich um keine Verträge handelt zur Erbringung von Dienstleistungen in den Bereichen Beherbergung zu anderen Zwecken als zu Wohnzwecken, Beförderung von Waren, Kraftfahrzeugvermietung, Lieferung von Speisen und Getränken sowie zur Erbringung weiterer Dienstleistungen im Zusammenhang mit Freizeitbetätigungen, wenn der Vertrag für die Erbringung einen spezifischen Termin oder Zeitraum vorsieht (vgl. § 312g Nr. 9 BGB), gilt folgendes Widerrufsrecht:</p>
                            <p><strong>Widerrufsbelehrung</strong> Widerrufsrecht <br> Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag des Vertragsabschlusses. Um Ihr Widerrufsrecht auszuüben, müssen Sie uns (Huetten-Holiday.de - Huetten-Holiday.GmbH, Nebelhornstr. 3, 87448 Waltenhofen Germany, Telefon: +49 (0) 9001 / 32 99 99(1,99 €/min aus dem dt. Festnetz, Mobilfunk ggf. abweichend), Telefax 0049 8303 / 32 99 89 - 9, E-Mail service@huetten-holiday.de) mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief, Telefax oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerru-fen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist. Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ab-lauf der Widerrufsfrist absenden. <br> Folgen des Widerrufs <br> Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich etwaiger Lieferkosten, unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mit-teilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Haben Sie verlangt, dass die Dienstleistungen während der Widerrufsfrist beginnen soll, so haben Sie uns einen angemessenen Betrag zu zahlen, der dem Anteil der bis zu dem Zeitpunkt, zu dem Sie uns von der Ausübung des Widerrufsrechts hinsichtlich die-ses Vertrags unterrichten, bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der im Vertrag vorgese-henen Dienstleistungen entspricht.</p>
                            <p>Muster-Widerrufsformular<br> (Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es zurück.) <br> An: Huetten-Holiday.GmbH<br> Nebelhornstr. 3<br> 87448 Waltenhofen<br> Germany <br> Telefax 0049 8303 / 32 99 89 - 9<br> service@huetten-holiday.de </p>
                            <ul>
                                <li>Hiermit widerrufe(n) ich / wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*) / die Erbringung der folgenden Dienstleistung</li>
                                <li>(*) - Bestellt am (*) / erhalten am (*)</li>
                                <li>Name des / der Verbraucher(s)</li>
                                <li>Anschrift des / der Verbraucher(s)</li>
                                <li>Unterschrift des / der Verbraucher(s) (nur bei Mitteilung auf Papier)</li>
                                <li>Datum ______</li>
                            </ul>
                            (*) Unzutreffendes streichen.
                            <p>&nbsp;</p>
                            <p>&nbsp;</p>
                        </li>
                        <li><strong>Verschiedenes</strong>
                            <ol>
                                <li>Übernahme von Daten Alle Angaben wurden mit größter Sorgfalt zusammengestellt. Für etwaige Fehler bei der Datenerfassung oder Datenüber-tragung kann jedoch keine Haftung übernommen werden.</li>
                                <li>Hinweis zum Widerrufsrecht hinsichtlich der Anmeldung Die Anmeldung beim Vermittler kann vom Kunden jederzeit schriftlich widerrufen werden. Auch ist der Vermittler berech-tigt, bei gewichtigem Grund die Anmeldung eines Kunden zu widerrufen. Der Vermittler behält sich außerdem das Recht vor, Kundenkontos mit unvollständigen, zweifelhaften oder augenscheinlich falschen Daten ohne Rücksprache mit dem Kunden zu deaktivieren. Dieses Recht besteht auch, wenn der Kunde in der Vergangenheit des Öfteren auffällig war, z.B. in Form von gehäufter Nichtanreise ohne Stornierung oder unbezahlten Rechnungen.</li>
                            </ol>
                        </li>
                        <li><strong>Erläuterungen zum Datenschutz</strong>
                            <p>Für weitere Informationen klicken Sie bitte hier.</p>
                        </li>
                        <li><strong>Gewährleistungsausschluss</strong>
                            <p>Das vom Vermittler betriebene Reservierungssystem ist ein für Sie unentgeltlicher Service. Deswegen übernimmt der Vermittler keine Gewährleistung für den Betrieb und die Nutzung des Reservierungssystems, insbesondere nicht für die folgenden Punkte: Für die Verfügbarkeit des Reservierungssystems und für die Möglichkeit, Reiseleistungen über das Reservierungssystem buchen zu können. Für die ordnungsgemäße Erfüllung des zwischen Ihnen und einem Anbieter von Reiseleistungen bestehenden Vertrages, auch wenn dieser Vertrag mit Hilfe des vom Vermittler betriebenen Reservie-rungssystems abgeschlossen wurde. Für die Möglichkeit, einen abgeschlossenen Vertrag mit Hilfe des Reservierungs-systems oder auch sonst, ändern oder stornieren zu können. Für die Richtigkeit und Vollständigkeit der in dem Reservie-rungssystem enthaltenen Beschreibungen der Reiseleistungen.</p>
                        </li>
                        <li><strong>Haftungsbeschränkung</strong>
                            <ol>
                                <li>Die Haftung des Vermittlers oder Reservierungssystembetreibers für alle Schäden, gleich aus welchem Rechtsgrund, einschließlich unerlaubter Handlung, quasivertraglicher Verpflichtung, Vertrag oder Gewährleistung, ist ausgeschlossen, soweit die Schäden nicht (i) durch eine schuldhafte Verletzung von vertragswesentlichen Pflichten durch den Vermittler in einer Weise, die den Vertragszweck gefährdet, oder (ii) durch grobe Fahrlässigkeit oder Vorsatz seitens des Vermittlers verursacht wurden, in Erfüllung oder bei Gelegenheit der Dienstleistungen.</li>
                                <li>Haftet der Vermittler gemäß Nr. 9.1(i) für die schuldhafte Verletzung von Kardinalpflichten, ohne dass grobe Fahrlässigkeit oder Vorsatz vorliegen, ist die gesamte Haftung des Vermittlers oder Reservierungssystembetreibers auf solche Schäden und einen solchen Schadensumfang beschränkt, deren Eintritt der Vermittler oder Reservierungssystembetreiber nach den ihm bei Vertragsschluss bekannten Umständen typischerweise voraussehen konnte. In Fällen dieser Nr. 9.1(ii). besteht keine Haftung des Vermittlers für mittelbare Schäden, Mängelfolgeschäden oder entgangenen Gewinn.</li>
                                <li>Haftet der Vermittler oder Reservierungssystembetreiber gemäß Nr. 9.1(ii) für grobe Fahrlässigkeit oder Vorsatz von Mitarbeitern oder Beauftragten, die nicht Organe oder leitende Angestellte des Vermittlers oder Reservierungssystembe-treibers sind, ist die gesamte Haftung des Vermittlers oder Reservierungssystembetreibers ebenfalls auf solche Schäden und einen solchen Schadensumfang begrenzt, deren Eintritt der Vermittler oder Reservierungssystembetreiber nach den ihm bei Vertragsschluss bekannten Umständen typischerweise voraussehen konnte. In Fällen dieser Nr. 9.3. besteht keine Haftung des Vermittlers oder Reservierungssystembetreibers für mittelbare Schäden, Mängelfolgeschäden oder entgange-nen Gewinn.</li>
                                <li>In den Fällen von Nr. 9.2. und 9.3. ist die gesamte Haftung des Vermittlers oder Reservierungssystembetreibers auf 50.000 EUR beschränkt. Die gesamte Haftung für reine Vermögensschäden (im Gegensatz zu Personen- oder Sachschäden) ist in diesen Fällen weitergehend beschränkt auf den Wert der Dienstleistungen. Schadensersatzansprüche verjähren spätes-tens ein Jahr nach dem Zeitpunkt, zu dem Sie vom schädigenden Ereignis erfahren haben. Dies gilt nicht für Ansprüche aus unerlaubter Haftung.</li>
                                <li>Der Ausschluss oder die Beschränkung der Schadensersatzhaftung gemäß den vorstehenden Vorschriften gilt auch für etwaige Ansprüche gegen Mitarbeiter oder Beauftragte des Vermittlers oder Reservierungssystembetreibers.</li>
                            </ol>
                        </li>
                        <li><strong>Copyright</strong>
                            <p>Die Bestandteile des vom Vermittler betriebenen Reservierungssystems unterliegen dem Urheberrecht und weiteren Schutzrechten. Die Benutzung der Webseiten des Vermittlers betriebenen Reservierungssystems und der dort gespeicher-ten Materialien ist nur zulässig, um Reservierungen über den Vermittler vorzunehmen.</p>
                        </li>
                        <li><strong>Anwendbares Recht</strong>
                            <p>Diese Geschäftsbedingungen und die zugrundeliegenden Verträge zwischen dem Kunden und dem Vermittler unterliegen dem Recht der Bundesrepublik Deutschland ohne dessen etwaigen Verweis auf ein anderes ausländisches Recht und unter Ausschluss des UN-Kaufrechts.</p>
                        </li>
                        <li><strong>Erfüllungsort &amp; Gerichtsstand</strong>
                            <p>Erfüllungsort ist Waltenhofen, Deutschland und Gerichtsstand ist Kempten, Deutschland, sofern der Kunde Unternehmer im Sinne von § 14 BGB ist.</p>
                        </li>
                        <li><strong>Salvatorische Klausel</strong>
                            <p>Sollte sich eine Bestimmung dieser Bedingungen als rechtlich unwirksam erweisen, so behält der restliche Teil seine volle Gültigkeit. An die Stelle der betreffenden Bestimmung tritt diejenige Regelung, die den gewünschten wirtschaftlichen Erfolg in rechtsgültiger Weise mindestens am nächsten kommt. Streitigkeiten, die im Zusammenhang mit diesem Vertrag entste-hen, sollen von den Vertragspartnern zunächst gütlich beigelegt werden.</p>
                        </li>
                    </ol>
                </article>
            </div>
        </div><br /><br />
    </main>
@endsection

